---
- name: Check ansible version
  ansible.builtin.fail:
    msg: Installed ansible version {{ ansible_version.full }}, but ansible version > 2.1.1.1 required
  when: ansible_version.full is version('2.9', '<')

- name: Check there is a valid way of acquiring an API key
  ansible.builtin.fail:
    msg: No API key for a Galaxy admin, or a boostrapping API key, was provided. Please see the docs for this role
  when: not galaxy_tools_api_key

- name: Create bootstrap user
  when: galaxy_tools_create_bootstrap_user
  ansible.builtin.include_tasks: bootstrap.yml

- name: Set API key to use for operations
  ansible.builtin.set_fact:
    galaxy_tools_ops_key: "{{ galaxy_tools_api_key }}"
  when: galaxy_tools_ops_key is not defined # if it is defined by bootstrap.yml, do not set this.

- name: Include tool installation tasks
  ansible.builtin.include_tasks: tools.yml
  when: galaxy_tools_install_tools

- name: Include data manager tasks
  ansible.builtin.include_tasks: data_managers.yml
  when: galaxy_tools_install_data_managers

- name: Include workflow installation tasks
  ansible.builtin.include_tasks: workflows.yml
  when: galaxy_tools_install_workflows

- name: Delete the bootstrapped admin user
  when: galaxy_tools_create_bootstrap_user and galaxy_tools_delete_bootstrap_user
  ansible.builtin.command:
    cmd: >
      {{ galaxy_tools_base_dir }}/manage_bootstrap_user.py
      -d
      -a {{ galaxy_tools_api_key }}
      -g {{ galaxy_tools_galaxy_instance_url }}
      -e {{ galaxy_tools_bootstrap_user_email }}
  register: _galaxy_delete_user
  changed_when: '"Deleted user" in _galaxy_delete_user.stdout'
