---
- name: Check ansible version
  fail:
    msg: "Installed ansible version {{ ansible_version.full }}, but ansible version > 2.1.1.1 required"
  when: ansible_version.full is version('2.1.1.1', '<')

- include_tasks: tools.yml
  when: galaxy_tools_install_tools

- include_tasks: data_managers.yml
  when: galaxy_tools_install_data_managers

- include_tasks: workflows.yml
  when: galaxy_tools_install_workflows
