---
- name: Stop Galaxy
  ansible.builtin.command: "{{ galaxy_tools_galaxy_server_dir }}/run.sh --pid-file={{ galaxy_tools_pid_file_name }} --log-file={{ galaxy_tools_log_file_name }} --stop-daemon"
  ignore_errors: true

- name: Wait for Galaxy to stop
  ansible.builtin.wait_for:
    port: "8080"
    delay: "5"
    state: stopped
    timeout: "150"
- name: Start Galaxy
  ansible.builtin.command: "{{ galaxy_tools_galaxy_server_dir }}/run.sh --pid-file={{ galaxy_tools_pid_file_name }} --log-file={{ galaxy_tools_log_file_name }} --daemon"
  become_user: "{{ galaxy_tools_galaxy_user_name }}"

- name: Wait for Galaxy to start
  ansible.builtin.wait_for:
    port: "8080"
    delay: "5"
    state: started
    timeout: "150"
