---
- name: Create/invoke script virtualenv (Workflows)
  ansible.builtin.pip:
    name:
      - pyyaml
      - bioblend~={{ galaxy_tools_bioblend_version }}
    state: present
    virtualenv: "{{ galaxy_tools_venv_dir }}"
    virtualenv_command: "{{ pip_virtualenv_command | default('virtualenv') }}"

- name: Place the tool management script
  ansible.builtin.copy:
    src: install_workflow.py
    dest: "{{ galaxy_tools_base_dir }}/install_workflow.py"
    mode: "0700"

- name: Copy workflows
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ galaxy_tools_base_dir }}/{{ item | basename }}"
    mode: "0640"
  with_items:
    - "{{ galaxy_tools_workflows }}"

- name: Install workflows
  ansible.builtin.command: >
    {{ galaxy_tools_venv_dir }}/bin/python install_workflow.py
    -w '{{ item | basename }}'
    -a {{ galaxy_tools_ops_key }}
    -g {{ galaxy_tools_galaxy_instance_url }}
    {% if galaxy_tools_galaxy_publish_workflows %}
    -p
    {% endif %}
  args:
    chdir: "{{ galaxy_tools_base_dir }}"
  register: _install_result
  retries: "{{ galaxy_tools_install_retries }}"
  delay: "{{ galaxy_tools_install_retry_delay }}"
  until: _install_result is not failed
  changed_when: "'Workflow already exists' not in _install_result.stdout"
  ignore_errors: "{{ galaxy_tools_ignore_errors }}"
  with_items:
    - "{{ galaxy_tools_workflows }}"
