---

- name: Create/invoke script virtualenv (Workflows)
  pip:
    name:
      - pyyaml
      - bioblend~={{ galaxy_tools_bioblend_version }}
    state: present
    virtualenv: "{{ galaxy_tools_venv_dir }}"
    virtualenv_command: "{{ pip_virtualenv_command | default( 'virtualenv' ) }}"

- name: Place the tool management script
  ansible.builtin.copy: 
    src: install_workflow.py
    dest: "{{ galaxy_tools_base_dir }}/install_workflow.py"

- name: Copy workflows
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ galaxy_tools_base_dir }}/{{ item | basename }}"
  with_items:
    - "{{ galaxy_tools_workflows }}"

- name: Install workflows
  ansible.builtin.command: "{{ galaxy_tools_venv_dir }}/bin/python install_workflow.py -w '{{ item | basename }}' -a {{ galaxy_tools_workflow_api_key }} -g {{ galaxy_tools_galaxy_instance_url }}"
  args:
    chdir: "{{ galaxy_tools_base_dir }}"
  register: _install_result
  changed_when: "'Workflow already exists' not in _install_result.stdout"
  with_items:
    - "{{ galaxy_tools_workflows }}"

- name: Remove workflow script
  ansible.builtin.file:
    dest: "{{ galaxy_tools_base_dir }}/install_workflow.py"
    state: absent
