FROM {{ item.image }}

USER root
RUN apt update && apt install -y \
    python3-virtualenv python3-setuptools
USER galaxy

RUN sed -i 's/galaxy:/galaxy:\n    bootstrap_admin_api_key: {{ item.bootstrap_key }}/' /galaxy/server/config/galaxy.yml
RUN sed -i 's/galaxy:/galaxy:\n    allow_user_deletion: true/' /galaxy/server/config/galaxy.yml
